[WIP] send native structs in table updates
eBay/libovsdb pull request #14
Opened 2019-07-28 23:00 UTC by vtolstov

Signed-off-by: Vasiliy Tolstov <v.tolstov@unistack.org>

2019-07-28 23:02 UTC, vtolstov commented
Don't over allocate memory for json Marshal/Unmarshal, but fill needed structs directly via reflect.
Also send native row structs in updates, so go-ovn does not need to convert it back, but use only type assertion.
Pr to go-ovn repo prepeared (now only convert logical switch operations)

2019-07-28 23:04 UTC, vtolstov commented
later we can generate row_types.go file from ovnnb schema files via go generate

2019-07-30 16:03 UTC, vtolstov commented
now it have ugly things to parse empty sets and bools. why in Connection table max_backoff passed via set ?

2019-07-30 21:21 UTC, hzhou8 commented
Thanks for working on this! I have some major comments:

1. We should not introduce any OVN specific code in libovsdb. In rawToRowUpdates(), it should be generic enough. All OVN specific code should be in go-ovn.

2. We may consider auto generate the code for any given OVSDB schema. The code generation tool should be in libovsdb. In go-ovn it can use this tool to generate code for processing.

What do you think?

(it's ok to continue your test this way as POC)

2019-07-30 21:28 UTC, vtolstov commented
@hzhou8 
1) this changes not only ovn related. This changes ovsdb related. So i think that this is proper place. For example i create SSL Connection and other structs to libovsdb. So when we create client for openvswitch db, we can work with native go structs  and not maps
2) code generator for libovsdb is fine it can generate needed structs for all message updates. But why it needed for go-ovn?

2019-07-31 12:32 UTC, vtolstov commented
@hzhou8 i'm finish pr.
i think that now it completed, also i'm ush to go-ovn repo some files that already uses this pr

2019-07-31 18:44 UTC, hzhou8 commented
Thanks @vtolstov ! I need to review it in more detail, but here are just some minor things:

1. Could you add more detailed description in the commit message?

2. The SSL/TCP const rename is not related to this change, so please split to another PR.

3. There are still "ovn" in comments. It is better to be removed.

2019-07-31 19:38 UTC, vtolstov commented
@hzhou8 thanks, if fix suggested

2019-08-02 02:26 UTC, hzhou8 requested changes

2019-08-02 02:26 UTC, hzhou8 commented on rpc_test.go
> +	// TODO fix and send valid row update
This is such a complex and big change. I'd like to see tests added for this update. For example, what's the expected tableUpdates generated by update() to call handler.Update, test if the result is equal to the expected.

2019-08-02 02:26 UTC, hzhou8 commented on client.go
> -	SSL             = "ssl"
Still unrelated changes :)

2019-08-02 02:26 UTC, hzhou8 commented on convert.go
> +func StructToMap(iface interface{}, tag string) (map[string]interface{}, error) {
Where are these functions used? Any examples? Tests?

2019-08-08 18:43 UTC, vtolstov commented
@hzhou8 any chance to get this merged? or i need to fix something more?

2019-08-08 19:19 UTC, hzhou8 commented
@vtolstov sorry that I was distracted last week, but I did spent some time reviewing it, and I am still not very clear about the purpose of this change. Is it purely for performance optimization (i.e. to avoid marshal/unmarshal) or is it also an interface change (i.e. the format changed of tableUpdates generated by update())? If it is for performance, then is there test result telling how much did it improve? It did add a lot more complexity and if the performance gain is small I would be hesitating. I didn't see enough tests to tell the purpose of the change. I probably need more time to write some tests myself to understand more about it. I am also requesting adding more tests for such big change to make sure there is no regression problem.

2019-08-08 19:31 UTC, vtolstov commented
Thanks, this is very small change for sending updates, most of the changes needed for go-ovn to get native structs from map.
Also this adds some basic validation of format of row updates that must be like in rfc. Older version of test sent invalid row update.
Format of row update not changed, mostly this changes to avoid marshal/unmarshal. And fills UUID

2019-08-08 19:32 UTC, vtolstov commented
So this is compatible change that not change for consumers anything.

2019-08-08 19:33 UTC, vtolstov commented
Mostly this is not have major speedup, but minimize unneeded allocations.

2019-08-27 04:42 UTC, hzhou8 requested changes
Hi @vtolstov, sorry for the slow response. I did some tests myself to understand the intent of the change. Please see my comments/questions inlined. In addition, here are some more general comments:

1. Please update the example/play_with_ovs.go, which is now broken by this change.

2. The module convert.go seems not used in this repo, so I guess it is supposed to be used as an API by other project, e.g. go-ovn, right? If so, please add basic test cases to test the interfaces and also as example to demonstrate how to use them.

3. If we want to treat this as a prototype and if adding documentation and test cases seem to be too heavy for the prototype phase, then I'd suggest to merge it to a branch instead of master. When the prototype is proved mature and all the documentation and tests are ready, we can merge it to master.

2019-08-27 04:42 UTC, hzhou8 commented on rpc_test.go
> +	// Valid dummy update should pass https://tools.ietf.org/html/rfc7047#section-4.1.6
Please update the comments, since you are now changing the test from testing a dummy update to testing a non-dummy update, i.e. with a new row insertion.

2019-08-27 04:42 UTC, hzhou8 commented on rpc_test.go
> +	updates["Test_Table"] = make(map[string]interface{})
This is not needed.

2019-08-27 04:42 UTC, hzhou8 commented on rpc_test.go
> +	tableUpdate["Test_UUID"] = make(map[string]interface{})
Not needed

2019-08-27 04:42 UTC, hzhou8 commented on rpc_test.go
> +	newUpdate["new"] = make(map[string]interface{})
Not needed

2019-08-27 04:42 UTC, hzhou8 commented on client.go
> +	for tbl, opt := range raw {
Why the variable named "opt" here? Is it more straightforward to be: "tblUpdate"?

2019-08-27 04:42 UTC, hzhou8 commented on client.go
> +		for uuid, val := range opts {
Suggest to rename "val" to "rowUpdate"

2019-08-27 04:42 UTC, hzhou8 commented on client.go
> +			return nil, fmt.Errorf("invalid row update: %v", opt)
Error message can be enhanced to "invalid TableUpdate"

2019-08-27 04:42 UTC, hzhou8 commented on client.go
> +		opts, ok := opt.(map[string]interface{})
opts => rowUpdates

2019-08-27 04:42 UTC, hzhou8 commented on client.go
> +					return nil, fmt.Errorf("invalid row update: %v", vv)
It is better to print "old" or "new" in the error message to help debugging

2019-08-27 04:42 UTC, hzhou8 commented on client.go
> +func rawToRowUpdates(raw map[string]interface{}) (map[string]map[string]RowUpdate, error) {
Originally, the rowUpdate uses Row struct, which has OvsMap, OvsSet, etc. embedded. Now this patch use a slice to represent the value of each column. For example, originally a column "external_ids" is like:

"external_ids":libovsdb.OvsMap{GoMap:map[interface {}]interface {}{"docker":"made-for-each-other", "go":"awesome"}}

Now it is changed to:
"external_ids":[]interface {}{"map", []interface {}{[]interface {}{"docker", "made-for-each-other"}, []interface {}{"go", "awesome"}}}

The first element in the slice is the string "map", probably representing the data type, and the second element is a slice of interface{}, each element representing a key-value pair in the "external_ids" column. Each key-value pair is again represented by a slice of interface{} which has two element: the first element is the key, and the second element is the value.

Is this slices of slices of slices the desired output of this function? How is it more "native" than the original implementation? Could you explain a little more? I think it is better to have some formal documentation to describe the design. I'd also insist to have some basic test cases to verify if the function behaves as expected, i.e. given some typical input of "raw", make sure the return value is expected as per the design.

2021-02-03 10:44 UTC, vtolstov commented
close in favour of #28

2021-02-03 10:44 UTC, closed without merging