Allow libovsdb to connnect to ovsdb instance over IPv6 connection.
eBay/libovsdb pull request #20
Opened 2020-07-17 13:59 UTC by Billy99

When trying to connect to an ovsdb instance via IPv6, encountered an IPv6
parsing issue. In the logic to strip off the leading protocol (i.e. tcp:...),
the code uses strings.Split(endpoint, ":"), which does not take into account
the ':' in an IPv6 address.

Updated the code to use strings.SplitN(endpoint, ":", 2) instead.

Signed-off-by: Billy McFall <22157057+Billy99@users.noreply.github.com>

2020-07-17 14:08 UTC, Billy99 commented on client.go
>  				host = defaultTCPAddress
I left the check for empty `host` as it was, but I think that check should be outside of the check for `endPointStr` length.

2020-07-17 14:36 UTC, vtolstov commented
i think that proper fix is to use url.Parse func, can you try to use it ?

2020-07-17 14:40 UTC, vtolstov requested changes
i'm against of strings.Split to parse endpoint. I'm prefer url.Parse

2020-07-17 14:41 UTC, Billy99 commented
OK, I'll give it a shot. I was trying to fix with minimal changes.

2020-07-19 06:20 UTC, hzhou8 commented
LGTM

2020-07-19 15:47 UTC, vtolstov approved these changes

2020-07-19 15:48 UTC, vtolstov commented
can you remove latest commit to get this merged?

2020-07-19 16:31 UTC, merged