Poc/orm
eBay/libovsdb pull request #31
Opened 2021-02-25 15:45 UTC by amorenoz

Following the idea drafted in #29 and based on the work done in #30, this PR adds a ORM-like API

## Why a ORM-like API?##
I'm opening to change the name (I'm very bad with names). The idea is to interact with libovsdb using native Objects (i.e: golang structs) instead of `map[string] interface{}`.
So, when I want to insert a Row, I can create an object, pass it to the library and it will take care of inserting it in the right table and perform the right native-to-ovs type conversions.

## How does it work? ##
Similarly to  #30, it uses the schema bindings to figure out the exact conversion needed for each column. But, how do we tell the library which field of my struct goes into what column? well, borrowing the idea from @vtolstov, I propose to use a struct tag called "ovs". 

The orm API then uses `reflect` to inspect the type of structure given and populate the fields accordingly.

### Example ###
This is an example of how you would use this API
```
type MyRow struct {
	Name      string            `ovs:"name"`
	SomeRef   []string          `ovs:"someRef"`
	ExtraConf map[string]string `ovs:"extra_config"`
}

# Parse incoming data from OVSDB (stored in 'rowData')
var aRow MyRow
ormAPI.GetRowData(TableName, rowData, &myRow)
fmt.Printf("Received a row named %s: %+v", aRow.Name, aRow)

# Format data to send to OVSDB
bRow := MyRow {
 Name: "foo",
 SomeRef: []string{"2f77b348-9768-4866-b761-89d5177ecda0"},
 ExtraConf: map[string] string {"foo": "bar"},
}
ovsRow, _ := ormAPI.NewRow(TableName, bRow)

```

##  Related work ##
Based on this API, I have created a PR in go-ovn that exposes a ORM API: 
Also, an example of a fully-blown go-ovn object-based API access that has been developed using this PR can be seen here: https://github.com/amorenoz/ovnmodel

2021-03-31 08:50 UTC, vtolstov commented
so the next step - rebasing?

2021-04-05 06:12 UTC, hzhou8 requested changes
It would be good to update example/play_with_ovs to use ORM API, too.

Also, I have one more question: now that we have ORM API, why do we still need the NativeAPI? Do you have some use cases in your mind where NativeAPI is preferred over ORM API?

2021-04-05 06:12 UTC, hzhou8 commented on orm.go
> +// 'ovn:"${COLUMN_NAME}"'
s/ovn/ovs

2021-04-05 06:12 UTC, hzhou8 commented on example/stress/stress.go
>  	if *api == "native" {
Add a branch to call ORM APIs here as well?

2021-04-05 11:36 UTC, amorenoz commented
> It would be good to update example/play_with_ovs to use ORM API, too.
> 
> Also, I have one more question: now that we have ORM API, why do we still need the NativeAPI? Do you have some use cases in your mind where NativeAPI is preferred over ORM API?

NativeAPI is still useful if you don't want to enforce strong type checking. For example, projects that closely follow a OVN version might as well use the ORM API with auto-generated models (I'll send a PR with the generator to go-ovn soon). One example of this might be ovn-k8s.
On the other hand, projects that need to work with a number of OVN versions (paying the cost of maybe adding some ad-hoc type-checking logic) might still want to use Native API. ovn-k8s might still want this intermediate API as a flexibility / friendliness tradeoff.
@palanik1, wdyt?

We discussed this a while back in #29, and you folks are more familiar with these projects and their ecosystem. Do you see a good  use case for NativeAPI after ORM API gets merged? I really only needed it to demonstrate the bindings worked properly.

2021-04-05 18:31 UTC, hzhou8 commented
> > It would be good to update example/play_with_ovs to use ORM API, too.
> > Also, I have one more question: now that we have ORM API, why do we still need the NativeAPI? Do you have some use cases in your mind where NativeAPI is preferred over ORM API?
> 
> NativeAPI is still useful if you don't want to enforce strong type checking. For example, projects that closely follow a OVN version might as well use the ORM API with auto-generated models (I'll send a PR with the generator to go-ovn soon). One example of this might be ovn-k8s.
> On the other hand, projects that need to work with a number of OVN versions (paying the cost of maybe adding some ad-hoc type-checking logic) might still want to use Native API. ovn-k8s might still want this intermediate API as a flexibility / friendliness tradeoff.
> @palanik1, wdyt?
> 
> We discussed this a while back in #29, and you folks are more familiar with these projects and their ecosystem. Do you see a good use case for NativeAPI after ORM API gets merged? I really only needed it to demonstrate the bindings worked properly.

For "projects that need to work with a number of OVN versions", can they generate multiple versions of APIs, so that they can support multiple versions of schemas, and let the end user (user of k8s) configure which version to be used when deploying through configuration?

I am thinking about removing NativeAPI support for now. When we are sure it is really necessary we can always bring them back. (Having it now and then stop supporting may cause more trouble/confusion for users)

2021-04-12 19:36 UTC, hzhou8 commented
Hi @amorenoz , would you still be updating this PR? (removing NativeAPI support can be separate PR, but would you address the other minor comments?)

2021-04-13 07:56 UTC, amorenoz commented
Hi @hzhou8. Yes. I'm rebasing this PR on top of #35. Also, I'm moving https://github.com/eBay/go-ovn/pull/136 (i.e: the CRUD API) on top. I hope to have it ready for an update later today.
However, I can close this PR and send the updated version to `socketplane`.

2021-04-13 12:41 UTC, palanik1 commented
@amorenoz For OVN-K we are wedded to the Client API atleast for now ( our mocks use it for testing). I would assume ORM vs Native is an implementation choice for go-ovn that in principle shouldnt affect go-ovn users as long as there is a consistent high-level API such as the one in client.go. 
I understand even the API can be auto-generated on a per-project basis, but as an intermediate step, if the client API remains consistent, I dont think moving to ORM would affect us.

@sdsen @trozet what do you guys think

2021-04-26 17:48 UTC, hzhou8 commented
This is resubmitted to upstream https://github.com/ovn-org/libovsdb/pull/78, so I close it here

2021-04-26 17:49 UTC, closed without merging